name: Rust

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build_release:
    runs-on: windows-latest
    name: "Release build for Windows"
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v3
      - name: Build release binary
        run: cargo build --release
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"
      - uses: actions/upload-artifact@v3
        with:
          name: nvc-windows
          path: target/release/nvc.exe

  build_macos_release:
    runs-on: macos-latest
    name: "Release build for macOS"
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v3
      - name: Build release binary
        run: cargo build --release
        env:
          LZMA_API_STATIC: "true"
      - name: Strip binary from debug symbols
        run: strip target/release/nvc
      - name: List dynamically linked libraries
        run: otool -L target/release/nvc
      - uses: actions/upload-artifact@v3
        with:
          name: nvc-macos
          path: target/release/nvc

  build_static_linux_binary:
    name: "Build static Linux binary"
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
          targets: x86_64-unknown-linux-musl
      - uses: Swatinem/rust-cache@v2
        with:
          key: static-linux-binary
      - name: Install musl tools
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends musl-tools
      - uses: actions/checkout@v3
      - name: Build release binary
        run: cargo build --release --target x86_64-unknown-linux-musl
      - name: Strip binary from debug symbols
        run: strip target/x86_64-unknown-linux-musl/release/nvc
      - uses: actions/upload-artifact@v3
        with:
          name: nvc-linux
          path: target/x86_64-unknown-linux-musl/release/nvc
